INSERT INTO users(is_moderator, reg_time, name, email, password) VALUES (1, '2021-12-06', 'Роман', 'mxhx23@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Пётр', 'mxhx1@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Екатерина', 'mxhx2@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Дарья', 'mxhx3@gmail.com', '1234'),
                                                                        (1, '2021-12-07', 'Даниил', 'mxhx4@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Евгений', 'mxhx5@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Артем', 'mxhx6@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Анастасия', 'mxhx7@gmail.com', '1234'),
                                                                        (0, '2021-12-07', 'Фёдор', 'mxhx8@gmail.com', '1234');
INSERT INTO captcha_codes (time, code, secret_code) VALUES ('2021-12-06', 'sad1', 'dsadsad'),
                                                           ('2021-12-07', 'asdgf23', '34567gfdsaw'),
                                                           ('2021-12-07', '13sdsa', 'asd232'),
                                                           ('2021-12-07', '12easafds', 'sadad'),
                                                           ('2021-12-07', 'sad1', '34462fgaASF'),
                                                           ('2021-12-07', 'ahsd#32sasxX', 'H&13sa'),
                                                           ('2021-12-07', 'sad1sad1123s', 'ASHD35sad11dsa'),
                                                           ('2021-12-07', 'sad1ds11', 'JHGASDk113sshhasd'),
                                                           ('2021-12-07', 'sadsaasdd1', 'sadjh332');
INSERT INTO global_settings (code, name, value) VALUES ('MULTIUSER_MODE', 'Многопользовательский режим ', 'NO'),
                                                       ('POST_PREMODERATION', 'Премодерация постов ', 'YES'),
                                                       ('STATISTICS_IS_PUBLIC ', 'Показывать всем статистику блога', 'YES');
INSERT INTO posts (is_active, text, time, title, moderation_status, view_count, moderator_id, user_id) VALUES (1, 'some text1', '2021-12-06', 'some title', 'NEW', 2, 1, 1),
                                                                                                              (1, 'some text2', '2021-12-07', 'some title', 'ACCEPTED', 2, 5, 9),
                                                                                                              (1, 'some text3', '2021-12-08', 'some title', 'ACCEPTED', 2, 5, 8),
                                                                                                              (1, 'some text4', '2021-12-10', 'some title', 'DECLINED', 2, 5, 7),
                                                                                                              (1, 'some text5', '2021-12-11', 'some title', 'NEW', 2, 5, 2);
INSERT INTO post_comments (text, time, post_id, user_id) VALUES ('some text1', '2021-12-10', 2, 1),
                                                                ('some text2', '2021-12-10', 2, 1),
                                                                ('some text3', '2021-12-11', 3, 1),
                                                                ('some text4', '2021-12-11', 3, 1),
                                                                ('some text5', '2021-12-11', 1, 1),
                                                                ('some text6', '2021-12-11', 3, 1),
                                                                ('some text7', '2021-12-10', 2, 1);
INSERT INTO post_votes (time, value, post_id, user_id) VALUES ('2021-12-06', 1, 2, 1),
                                                              ('2021-12-06', 0, 2, 2),
                                                              ('2021-12-06', 1, 3, 3),
                                                              ('2021-12-06', 0, 3, 4),
                                                              ('2021-12-06', 1, 3, 5);
INSERT INTO tags (name) VALUES ('some text1'),
                               ('some text2'),
                               ('some text3'),
                               ('some text4');
INSERT INTO tag2post (post_id, tag_id) VALUES (2, 1),
                                              (2, 2),
                                              (2, 3),
                                              (2, 3),
                                              (3, 4),
                                              (3, 4),
                                              (3, 4);
