spring.datasource.url: jdbc:mysql://localhost:3306/lib
spring.datasource.username: root
spring.datasource.password: 80958095
spring.jpa.hibernate.ddl-auto: update
server.port: 80
spring.datasource.initialization-mode: always

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 999 195-24-84
blog.email: mxhx23@gmail.com
blog.copyright: Роман Владимиров
blog.copyrightFrom: 2021

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: t232421123@gmail.com
spring.mail.password: _E7:aX-n52XTrje
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

spring.servlet.multipart.max-file-size: 5MB
spring.servlet.multipart.max-request-size: 5MB

spring.profiles.active: dev


