spring.datasource.url: jdbc:mysql://localhost:3306/lib
spring.datasource.username: root
spring.datasource.password: 80958095
spring.jpa.hibernate.ddl-auto: update

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: t232421123@gmail.com
spring.mail.password: _E7:aX-n52XTrje
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

spring.servlet.multipart.max-file-size: 5MB
spring.servlet.multipart.max-request-size: 5MB


